[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
graphql_client = { version = "0.13.0", features = ["reqwest-blocking"] }
serde = "^1.0"
reqwest = { version = "0.11", features = ["blocking", "json", "native-tls-vendored"] }
